# Generated by Django 3.2 on 2021-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='open', max_length=100),
        ),
    ]
