# Generated by Django 3.2 on 2021-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='open', max_length=100),
        ),
    ]
