# Generated by Django 3.2 on 2021-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_verify_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
