# Generated by Django 3.2 on 2021-04-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210422_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
    ]
